//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ITintheDTestModel1", "fk_RoleId", "webpages_Roles", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ITinTheDWebSite.webpages_Roles), "webpages_UsersInRoles", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ITinTheDWebSite.webpages_UsersInRoles), true)]
[assembly: EdmRelationshipAttribute("ITintheDTestModel1", "FK_ProspectiveAcademic_AcademicStatus1", "AcademicStatus", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ITinTheDWebSite.AcademicStatus), "ProspectiveAcademic", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ITinTheDWebSite.ProspectiveAcademic), true)]
[assembly: EdmRelationshipAttribute("ITintheDTestModel1", "FK_ProspectiveCorporateSponsor_SponsorStatus", "SponsorStatu", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ITinTheDWebSite.SponsorStatu), "ProspectiveCorporateSponsor", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ITinTheDWebSite.ProspectiveCorporateSponsor), true)]
[assembly: EdmRelationshipAttribute("ITintheDTestModel1", "FK_ProspectiveStudent_StudentStatus1", "StudentStatu", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ITinTheDWebSite.StudentStatu), "ProspectiveStudent", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ITinTheDWebSite.ProspectiveStudent), true)]

#endregion

namespace ITinTheDWebSite
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ITintheDTestTableEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ITintheDTestTableEntities object using the connection string found in the 'ITintheDTestTableEntities' section of the application configuration file.
        /// </summary>
        public ITintheDTestTableEntities() : base("name=ITintheDTestTableEntities", "ITintheDTestTableEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ITintheDTestTableEntities object.
        /// </summary>
        public ITintheDTestTableEntities(string connectionString) : base(connectionString, "ITintheDTestTableEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ITintheDTestTableEntities object.
        /// </summary>
        public ITintheDTestTableEntities(EntityConnection connection) : base(connection, "ITintheDTestTableEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Faq> Faqs
        {
            get
            {
                if ((_Faqs == null))
                {
                    _Faqs = base.CreateObjectSet<Faq>("Faqs");
                }
                return _Faqs;
            }
        }
        private ObjectSet<Faq> _Faqs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ProspectiveStudentResume> ProspectiveStudentResumes
        {
            get
            {
                if ((_ProspectiveStudentResumes == null))
                {
                    _ProspectiveStudentResumes = base.CreateObjectSet<ProspectiveStudentResume>("ProspectiveStudentResumes");
                }
                return _ProspectiveStudentResumes;
            }
        }
        private ObjectSet<ProspectiveStudentResume> _ProspectiveStudentResumes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ProspectiveStudentTranscript> ProspectiveStudentTranscripts
        {
            get
            {
                if ((_ProspectiveStudentTranscripts == null))
                {
                    _ProspectiveStudentTranscripts = base.CreateObjectSet<ProspectiveStudentTranscript>("ProspectiveStudentTranscripts");
                }
                return _ProspectiveStudentTranscripts;
            }
        }
        private ObjectSet<ProspectiveStudentTranscript> _ProspectiveStudentTranscripts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<webpages_Roles> webpages_Roles
        {
            get
            {
                if ((_webpages_Roles == null))
                {
                    _webpages_Roles = base.CreateObjectSet<webpages_Roles>("webpages_Roles");
                }
                return _webpages_Roles;
            }
        }
        private ObjectSet<webpages_Roles> _webpages_Roles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<webpages_UsersInRoles> webpages_UsersInRoles
        {
            get
            {
                if ((_webpages_UsersInRoles == null))
                {
                    _webpages_UsersInRoles = base.CreateObjectSet<webpages_UsersInRoles>("webpages_UsersInRoles");
                }
                return _webpages_UsersInRoles;
            }
        }
        private ObjectSet<webpages_UsersInRoles> _webpages_UsersInRoles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AcademicStatus> AcademicStatus
        {
            get
            {
                if ((_AcademicStatus == null))
                {
                    _AcademicStatus = base.CreateObjectSet<AcademicStatus>("AcademicStatus");
                }
                return _AcademicStatus;
            }
        }
        private ObjectSet<AcademicStatus> _AcademicStatus;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<StudentStatu> StudentStatus
        {
            get
            {
                if ((_StudentStatus == null))
                {
                    _StudentStatus = base.CreateObjectSet<StudentStatu>("StudentStatus");
                }
                return _StudentStatus;
            }
        }
        private ObjectSet<StudentStatu> _StudentStatus;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SponsorStatu> SponsorStatus
        {
            get
            {
                if ((_SponsorStatus == null))
                {
                    _SponsorStatus = base.CreateObjectSet<SponsorStatu>("SponsorStatus");
                }
                return _SponsorStatus;
            }
        }
        private ObjectSet<SponsorStatu> _SponsorStatus;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ProspectiveAcademic> ProspectiveAcademic
        {
            get
            {
                if ((_ProspectiveAcademic == null))
                {
                    _ProspectiveAcademic = base.CreateObjectSet<ProspectiveAcademic>("ProspectiveAcademic");
                }
                return _ProspectiveAcademic;
            }
        }
        private ObjectSet<ProspectiveAcademic> _ProspectiveAcademic;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ProspectiveCorporateSponsor> ProspectiveCorporateSponsor
        {
            get
            {
                if ((_ProspectiveCorporateSponsor == null))
                {
                    _ProspectiveCorporateSponsor = base.CreateObjectSet<ProspectiveCorporateSponsor>("ProspectiveCorporateSponsor");
                }
                return _ProspectiveCorporateSponsor;
            }
        }
        private ObjectSet<ProspectiveCorporateSponsor> _ProspectiveCorporateSponsor;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ProspectiveStudent> ProspectiveStudent
        {
            get
            {
                if ((_ProspectiveStudent == null))
                {
                    _ProspectiveStudent = base.CreateObjectSet<ProspectiveStudent>("ProspectiveStudent");
                }
                return _ProspectiveStudent;
            }
        }
        private ObjectSet<ProspectiveStudent> _ProspectiveStudent;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Faqs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFaqs(Faq faq)
        {
            base.AddObject("Faqs", faq);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ProspectiveStudentResumes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProspectiveStudentResumes(ProspectiveStudentResume prospectiveStudentResume)
        {
            base.AddObject("ProspectiveStudentResumes", prospectiveStudentResume);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ProspectiveStudentTranscripts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProspectiveStudentTranscripts(ProspectiveStudentTranscript prospectiveStudentTranscript)
        {
            base.AddObject("ProspectiveStudentTranscripts", prospectiveStudentTranscript);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the webpages_Roles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTowebpages_Roles(webpages_Roles webpages_Roles)
        {
            base.AddObject("webpages_Roles", webpages_Roles);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the webpages_UsersInRoles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTowebpages_UsersInRoles(webpages_UsersInRoles webpages_UsersInRoles)
        {
            base.AddObject("webpages_UsersInRoles", webpages_UsersInRoles);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AcademicStatus EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAcademicStatus(AcademicStatus academicStatus)
        {
            base.AddObject("AcademicStatus", academicStatus);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the StudentStatus EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStudentStatus(StudentStatu studentStatu)
        {
            base.AddObject("StudentStatus", studentStatu);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SponsorStatus EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSponsorStatus(SponsorStatu sponsorStatu)
        {
            base.AddObject("SponsorStatus", sponsorStatu);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ProspectiveAcademic EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProspectiveAcademic(ProspectiveAcademic prospectiveAcademic)
        {
            base.AddObject("ProspectiveAcademic", prospectiveAcademic);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ProspectiveCorporateSponsor EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProspectiveCorporateSponsor(ProspectiveCorporateSponsor prospectiveCorporateSponsor)
        {
            base.AddObject("ProspectiveCorporateSponsor", prospectiveCorporateSponsor);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ProspectiveStudent EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProspectiveStudent(ProspectiveStudent prospectiveStudent)
        {
            base.AddObject("ProspectiveStudent", prospectiveStudent);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ITintheDTestModel1", Name="AcademicStatus")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AcademicStatus : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AcademicStatus object.
        /// </summary>
        /// <param name="academicStatusId">Initial value of the AcademicStatusId property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        public static AcademicStatus CreateAcademicStatus(global::System.Int32 academicStatusId, global::System.String description)
        {
            AcademicStatus academicStatus = new AcademicStatus();
            academicStatus.AcademicStatusId = academicStatusId;
            academicStatus.Description = description;
            return academicStatus;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AcademicStatusId
        {
            get
            {
                return _AcademicStatusId;
            }
            set
            {
                if (_AcademicStatusId != value)
                {
                    OnAcademicStatusIdChanging(value);
                    ReportPropertyChanging("AcademicStatusId");
                    _AcademicStatusId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AcademicStatusId");
                    OnAcademicStatusIdChanged();
                }
            }
        }
        private global::System.Int32 _AcademicStatusId;
        partial void OnAcademicStatusIdChanging(global::System.Int32 value);
        partial void OnAcademicStatusIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ITintheDTestModel1", "FK_ProspectiveAcademic_AcademicStatus1", "ProspectiveAcademic")]
        public EntityCollection<ProspectiveAcademic> ProspectiveAcademic
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ProspectiveAcademic>("ITintheDTestModel1.FK_ProspectiveAcademic_AcademicStatus1", "ProspectiveAcademic");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ProspectiveAcademic>("ITintheDTestModel1.FK_ProspectiveAcademic_AcademicStatus1", "ProspectiveAcademic", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ITintheDTestModel1", Name="Faq")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Faq : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Faq object.
        /// </summary>
        /// <param name="faqID">Initial value of the FaqID property.</param>
        public static Faq CreateFaq(global::System.Int32 faqID)
        {
            Faq faq = new Faq();
            faq.FaqID = faqID;
            return faq;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FaqID
        {
            get
            {
                return _FaqID;
            }
            set
            {
                if (_FaqID != value)
                {
                    OnFaqIDChanging(value);
                    ReportPropertyChanging("FaqID");
                    _FaqID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("FaqID");
                    OnFaqIDChanged();
                }
            }
        }
        private global::System.Int32 _FaqID;
        partial void OnFaqIDChanging(global::System.Int32 value);
        partial void OnFaqIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Question
        {
            get
            {
                return _Question;
            }
            set
            {
                OnQuestionChanging(value);
                ReportPropertyChanging("Question");
                _Question = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Question");
                OnQuestionChanged();
            }
        }
        private global::System.String _Question;
        partial void OnQuestionChanging(global::System.String value);
        partial void OnQuestionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Answer
        {
            get
            {
                return _Answer;
            }
            set
            {
                OnAnswerChanging(value);
                ReportPropertyChanging("Answer");
                _Answer = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Answer");
                OnAnswerChanged();
            }
        }
        private global::System.String _Answer;
        partial void OnAnswerChanging(global::System.String value);
        partial void OnAnswerChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ITintheDTestModel1", Name="ProspectiveAcademic")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ProspectiveAcademic : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ProspectiveAcademic object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="academicId">Initial value of the AcademicId property.</param>
        /// <param name="status">Initial value of the Status property.</param>
        /// <param name="academyName">Initial value of the AcademyName property.</param>
        /// <param name="primaryContactName">Initial value of the PrimaryContactName property.</param>
        /// <param name="primaryEmailAddress">Initial value of the PrimaryEmailAddress property.</param>
        public static ProspectiveAcademic CreateProspectiveAcademic(global::System.Int32 id, global::System.Int32 academicId, global::System.Int32 status, global::System.String academyName, global::System.String primaryContactName, global::System.String primaryEmailAddress)
        {
            ProspectiveAcademic prospectiveAcademic = new ProspectiveAcademic();
            prospectiveAcademic.ID = id;
            prospectiveAcademic.AcademicId = academicId;
            prospectiveAcademic.Status = status;
            prospectiveAcademic.AcademyName = academyName;
            prospectiveAcademic.PrimaryContactName = primaryContactName;
            prospectiveAcademic.PrimaryEmailAddress = primaryEmailAddress;
            return prospectiveAcademic;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AcademicId
        {
            get
            {
                return _AcademicId;
            }
            set
            {
                OnAcademicIdChanging(value);
                ReportPropertyChanging("AcademicId");
                _AcademicId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AcademicId");
                OnAcademicIdChanged();
            }
        }
        private global::System.Int32 _AcademicId;
        partial void OnAcademicIdChanging(global::System.Int32 value);
        partial void OnAcademicIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.Int32 _Status;
        partial void OnStatusChanging(global::System.Int32 value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AcademyName
        {
            get
            {
                return _AcademyName;
            }
            set
            {
                OnAcademyNameChanging(value);
                ReportPropertyChanging("AcademyName");
                _AcademyName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AcademyName");
                OnAcademyNameChanged();
            }
        }
        private global::System.String _AcademyName;
        partial void OnAcademyNameChanging(global::System.String value);
        partial void OnAcademyNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AcademyAddress
        {
            get
            {
                return _AcademyAddress;
            }
            set
            {
                OnAcademyAddressChanging(value);
                ReportPropertyChanging("AcademyAddress");
                _AcademyAddress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AcademyAddress");
                OnAcademyAddressChanged();
            }
        }
        private global::System.String _AcademyAddress;
        partial void OnAcademyAddressChanging(global::System.String value);
        partial void OnAcademyAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PrimaryContactName
        {
            get
            {
                return _PrimaryContactName;
            }
            set
            {
                OnPrimaryContactNameChanging(value);
                ReportPropertyChanging("PrimaryContactName");
                _PrimaryContactName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PrimaryContactName");
                OnPrimaryContactNameChanged();
            }
        }
        private global::System.String _PrimaryContactName;
        partial void OnPrimaryContactNameChanging(global::System.String value);
        partial void OnPrimaryContactNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PrimaryTitle
        {
            get
            {
                return _PrimaryTitle;
            }
            set
            {
                OnPrimaryTitleChanging(value);
                ReportPropertyChanging("PrimaryTitle");
                _PrimaryTitle = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PrimaryTitle");
                OnPrimaryTitleChanged();
            }
        }
        private global::System.String _PrimaryTitle;
        partial void OnPrimaryTitleChanging(global::System.String value);
        partial void OnPrimaryTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PrimaryTelephone
        {
            get
            {
                return _PrimaryTelephone;
            }
            set
            {
                OnPrimaryTelephoneChanging(value);
                ReportPropertyChanging("PrimaryTelephone");
                _PrimaryTelephone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PrimaryTelephone");
                OnPrimaryTelephoneChanged();
            }
        }
        private global::System.String _PrimaryTelephone;
        partial void OnPrimaryTelephoneChanging(global::System.String value);
        partial void OnPrimaryTelephoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PrimaryEmailAddress
        {
            get
            {
                return _PrimaryEmailAddress;
            }
            set
            {
                OnPrimaryEmailAddressChanging(value);
                ReportPropertyChanging("PrimaryEmailAddress");
                _PrimaryEmailAddress = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PrimaryEmailAddress");
                OnPrimaryEmailAddressChanged();
            }
        }
        private global::System.String _PrimaryEmailAddress;
        partial void OnPrimaryEmailAddressChanging(global::System.String value);
        partial void OnPrimaryEmailAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SecondaryContactName
        {
            get
            {
                return _SecondaryContactName;
            }
            set
            {
                OnSecondaryContactNameChanging(value);
                ReportPropertyChanging("SecondaryContactName");
                _SecondaryContactName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SecondaryContactName");
                OnSecondaryContactNameChanged();
            }
        }
        private global::System.String _SecondaryContactName;
        partial void OnSecondaryContactNameChanging(global::System.String value);
        partial void OnSecondaryContactNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SecondaryTitle
        {
            get
            {
                return _SecondaryTitle;
            }
            set
            {
                OnSecondaryTitleChanging(value);
                ReportPropertyChanging("SecondaryTitle");
                _SecondaryTitle = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SecondaryTitle");
                OnSecondaryTitleChanged();
            }
        }
        private global::System.String _SecondaryTitle;
        partial void OnSecondaryTitleChanging(global::System.String value);
        partial void OnSecondaryTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SecondaryTelephone
        {
            get
            {
                return _SecondaryTelephone;
            }
            set
            {
                OnSecondaryTelephoneChanging(value);
                ReportPropertyChanging("SecondaryTelephone");
                _SecondaryTelephone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SecondaryTelephone");
                OnSecondaryTelephoneChanged();
            }
        }
        private global::System.String _SecondaryTelephone;
        partial void OnSecondaryTelephoneChanging(global::System.String value);
        partial void OnSecondaryTelephoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SecondaryEmailAddress
        {
            get
            {
                return _SecondaryEmailAddress;
            }
            set
            {
                OnSecondaryEmailAddressChanging(value);
                ReportPropertyChanging("SecondaryEmailAddress");
                _SecondaryEmailAddress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SecondaryEmailAddress");
                OnSecondaryEmailAddressChanged();
            }
        }
        private global::System.String _SecondaryEmailAddress;
        partial void OnSecondaryEmailAddressChanging(global::System.String value);
        partial void OnSecondaryEmailAddressChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ITintheDTestModel1", "FK_ProspectiveAcademic_AcademicStatus1", "AcademicStatus")]
        public AcademicStatus AcademicStatus
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AcademicStatus>("ITintheDTestModel1.FK_ProspectiveAcademic_AcademicStatus1", "AcademicStatus").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AcademicStatus>("ITintheDTestModel1.FK_ProspectiveAcademic_AcademicStatus1", "AcademicStatus").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<AcademicStatus> AcademicStatusReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AcademicStatus>("ITintheDTestModel1.FK_ProspectiveAcademic_AcademicStatus1", "AcademicStatus");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<AcademicStatus>("ITintheDTestModel1.FK_ProspectiveAcademic_AcademicStatus1", "AcademicStatus", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ITintheDTestModel1", Name="ProspectiveCorporateSponsor")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ProspectiveCorporateSponsor : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ProspectiveCorporateSponsor object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="sponsorId">Initial value of the SponsorId property.</param>
        /// <param name="status">Initial value of the Status property.</param>
        /// <param name="companyName">Initial value of the CompanyName property.</param>
        /// <param name="contactName">Initial value of the ContactName property.</param>
        /// <param name="emailAddress">Initial value of the EmailAddress property.</param>
        public static ProspectiveCorporateSponsor CreateProspectiveCorporateSponsor(global::System.Int32 id, global::System.Int32 sponsorId, global::System.Int32 status, global::System.String companyName, global::System.String contactName, global::System.String emailAddress)
        {
            ProspectiveCorporateSponsor prospectiveCorporateSponsor = new ProspectiveCorporateSponsor();
            prospectiveCorporateSponsor.ID = id;
            prospectiveCorporateSponsor.SponsorId = sponsorId;
            prospectiveCorporateSponsor.Status = status;
            prospectiveCorporateSponsor.CompanyName = companyName;
            prospectiveCorporateSponsor.ContactName = contactName;
            prospectiveCorporateSponsor.EmailAddress = emailAddress;
            return prospectiveCorporateSponsor;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SponsorId
        {
            get
            {
                return _SponsorId;
            }
            set
            {
                OnSponsorIdChanging(value);
                ReportPropertyChanging("SponsorId");
                _SponsorId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SponsorId");
                OnSponsorIdChanged();
            }
        }
        private global::System.Int32 _SponsorId;
        partial void OnSponsorIdChanging(global::System.Int32 value);
        partial void OnSponsorIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.Int32 _Status;
        partial void OnStatusChanging(global::System.Int32 value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CompanyName
        {
            get
            {
                return _CompanyName;
            }
            set
            {
                OnCompanyNameChanging(value);
                ReportPropertyChanging("CompanyName");
                _CompanyName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CompanyName");
                OnCompanyNameChanged();
            }
        }
        private global::System.String _CompanyName;
        partial void OnCompanyNameChanging(global::System.String value);
        partial void OnCompanyNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CompanyAddress
        {
            get
            {
                return _CompanyAddress;
            }
            set
            {
                OnCompanyAddressChanging(value);
                ReportPropertyChanging("CompanyAddress");
                _CompanyAddress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CompanyAddress");
                OnCompanyAddressChanged();
            }
        }
        private global::System.String _CompanyAddress;
        partial void OnCompanyAddressChanging(global::System.String value);
        partial void OnCompanyAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ContactName
        {
            get
            {
                return _ContactName;
            }
            set
            {
                OnContactNameChanging(value);
                ReportPropertyChanging("ContactName");
                _ContactName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ContactName");
                OnContactNameChanged();
            }
        }
        private global::System.String _ContactName;
        partial void OnContactNameChanging(global::System.String value);
        partial void OnContactNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Telephone
        {
            get
            {
                return _Telephone;
            }
            set
            {
                OnTelephoneChanging(value);
                ReportPropertyChanging("Telephone");
                _Telephone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Telephone");
                OnTelephoneChanged();
            }
        }
        private global::System.String _Telephone;
        partial void OnTelephoneChanging(global::System.String value);
        partial void OnTelephoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EmailAddress
        {
            get
            {
                return _EmailAddress;
            }
            set
            {
                OnEmailAddressChanging(value);
                ReportPropertyChanging("EmailAddress");
                _EmailAddress = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EmailAddress");
                OnEmailAddressChanged();
            }
        }
        private global::System.String _EmailAddress;
        partial void OnEmailAddressChanging(global::System.String value);
        partial void OnEmailAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Reason
        {
            get
            {
                return _Reason;
            }
            set
            {
                OnReasonChanging(value);
                ReportPropertyChanging("Reason");
                _Reason = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Reason");
                OnReasonChanged();
            }
        }
        private global::System.String _Reason;
        partial void OnReasonChanging(global::System.String value);
        partial void OnReasonChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ITintheDTestModel1", "FK_ProspectiveCorporateSponsor_SponsorStatus", "SponsorStatu")]
        public SponsorStatu SponsorStatus
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SponsorStatu>("ITintheDTestModel1.FK_ProspectiveCorporateSponsor_SponsorStatus", "SponsorStatu").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SponsorStatu>("ITintheDTestModel1.FK_ProspectiveCorporateSponsor_SponsorStatus", "SponsorStatu").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SponsorStatu> SponsorStatusReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SponsorStatu>("ITintheDTestModel1.FK_ProspectiveCorporateSponsor_SponsorStatus", "SponsorStatu");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SponsorStatu>("ITintheDTestModel1.FK_ProspectiveCorporateSponsor_SponsorStatus", "SponsorStatu", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ITintheDTestModel1", Name="ProspectiveStudent")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ProspectiveStudent : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ProspectiveStudent object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="status">Initial value of the Status property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="emailAddress">Initial value of the EmailAddress property.</param>
        public static ProspectiveStudent CreateProspectiveStudent(global::System.Int32 id, global::System.Int32 userId, global::System.Int32 status, global::System.String name, global::System.String emailAddress)
        {
            ProspectiveStudent prospectiveStudent = new ProspectiveStudent();
            prospectiveStudent.ID = id;
            prospectiveStudent.UserId = userId;
            prospectiveStudent.Status = status;
            prospectiveStudent.Name = name;
            prospectiveStudent.EmailAddress = emailAddress;
            return prospectiveStudent;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.Int32 _Status;
        partial void OnStatusChanging(global::System.Int32 value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Telephone
        {
            get
            {
                return _Telephone;
            }
            set
            {
                OnTelephoneChanging(value);
                ReportPropertyChanging("Telephone");
                _Telephone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Telephone");
                OnTelephoneChanged();
            }
        }
        private global::System.String _Telephone;
        partial void OnTelephoneChanging(global::System.String value);
        partial void OnTelephoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EmailAddress
        {
            get
            {
                return _EmailAddress;
            }
            set
            {
                OnEmailAddressChanging(value);
                ReportPropertyChanging("EmailAddress");
                _EmailAddress = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EmailAddress");
                OnEmailAddressChanged();
            }
        }
        private global::System.String _EmailAddress;
        partial void OnEmailAddressChanging(global::System.String value);
        partial void OnEmailAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DesiredCareerPath
        {
            get
            {
                return _DesiredCareerPath;
            }
            set
            {
                OnDesiredCareerPathChanging(value);
                ReportPropertyChanging("DesiredCareerPath");
                _DesiredCareerPath = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DesiredCareerPath");
                OnDesiredCareerPathChanged();
            }
        }
        private global::System.String _DesiredCareerPath;
        partial void OnDesiredCareerPathChanging(global::System.String value);
        partial void OnDesiredCareerPathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Gender
        {
            get
            {
                return _Gender;
            }
            set
            {
                OnGenderChanging(value);
                ReportPropertyChanging("Gender");
                _Gender = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Gender");
                OnGenderChanged();
            }
        }
        private global::System.String _Gender;
        partial void OnGenderChanging(global::System.String value);
        partial void OnGenderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ResumeUploaded
        {
            get
            {
                return _ResumeUploaded;
            }
            set
            {
                OnResumeUploadedChanging(value);
                ReportPropertyChanging("ResumeUploaded");
                _ResumeUploaded = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ResumeUploaded");
                OnResumeUploadedChanged();
            }
        }
        private global::System.String _ResumeUploaded;
        partial void OnResumeUploadedChanging(global::System.String value);
        partial void OnResumeUploadedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TranscriptUploaded
        {
            get
            {
                return _TranscriptUploaded;
            }
            set
            {
                OnTranscriptUploadedChanging(value);
                ReportPropertyChanging("TranscriptUploaded");
                _TranscriptUploaded = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TranscriptUploaded");
                OnTranscriptUploadedChanged();
            }
        }
        private global::System.String _TranscriptUploaded;
        partial void OnTranscriptUploadedChanging(global::System.String value);
        partial void OnTranscriptUploadedChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ITintheDTestModel1", "FK_ProspectiveStudent_StudentStatus1", "StudentStatu")]
        public StudentStatu StudentStatus
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<StudentStatu>("ITintheDTestModel1.FK_ProspectiveStudent_StudentStatus1", "StudentStatu").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<StudentStatu>("ITintheDTestModel1.FK_ProspectiveStudent_StudentStatus1", "StudentStatu").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<StudentStatu> StudentStatusReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<StudentStatu>("ITintheDTestModel1.FK_ProspectiveStudent_StudentStatus1", "StudentStatu");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<StudentStatu>("ITintheDTestModel1.FK_ProspectiveStudent_StudentStatus1", "StudentStatu", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ITintheDTestModel1", Name="ProspectiveStudentResume")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ProspectiveStudentResume : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ProspectiveStudentResume object.
        /// </summary>
        /// <param name="fileId">Initial value of the FileId property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="fileName">Initial value of the FileName property.</param>
        /// <param name="fileContent">Initial value of the FileContent property.</param>
        /// <param name="contentType">Initial value of the ContentType property.</param>
        /// <param name="contentLength">Initial value of the ContentLength property.</param>
        public static ProspectiveStudentResume CreateProspectiveStudentResume(global::System.Int32 fileId, global::System.Int32 userId, global::System.String fileName, global::System.Byte[] fileContent, global::System.String contentType, global::System.Int32 contentLength)
        {
            ProspectiveStudentResume prospectiveStudentResume = new ProspectiveStudentResume();
            prospectiveStudentResume.FileId = fileId;
            prospectiveStudentResume.UserId = userId;
            prospectiveStudentResume.FileName = fileName;
            prospectiveStudentResume.FileContent = fileContent;
            prospectiveStudentResume.ContentType = contentType;
            prospectiveStudentResume.ContentLength = contentLength;
            return prospectiveStudentResume;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FileId
        {
            get
            {
                return _FileId;
            }
            set
            {
                if (_FileId != value)
                {
                    OnFileIdChanging(value);
                    ReportPropertyChanging("FileId");
                    _FileId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("FileId");
                    OnFileIdChanged();
                }
            }
        }
        private global::System.Int32 _FileId;
        partial void OnFileIdChanging(global::System.Int32 value);
        partial void OnFileIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FileName
        {
            get
            {
                return _FileName;
            }
            set
            {
                OnFileNameChanging(value);
                ReportPropertyChanging("FileName");
                _FileName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FileName");
                OnFileNameChanged();
            }
        }
        private global::System.String _FileName;
        partial void OnFileNameChanging(global::System.String value);
        partial void OnFileNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] FileContent
        {
            get
            {
                return StructuralObject.GetValidValue(_FileContent);
            }
            set
            {
                OnFileContentChanging(value);
                ReportPropertyChanging("FileContent");
                _FileContent = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FileContent");
                OnFileContentChanged();
            }
        }
        private global::System.Byte[] _FileContent;
        partial void OnFileContentChanging(global::System.Byte[] value);
        partial void OnFileContentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ContentType
        {
            get
            {
                return _ContentType;
            }
            set
            {
                OnContentTypeChanging(value);
                ReportPropertyChanging("ContentType");
                _ContentType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ContentType");
                OnContentTypeChanged();
            }
        }
        private global::System.String _ContentType;
        partial void OnContentTypeChanging(global::System.String value);
        partial void OnContentTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ContentLength
        {
            get
            {
                return _ContentLength;
            }
            set
            {
                OnContentLengthChanging(value);
                ReportPropertyChanging("ContentLength");
                _ContentLength = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ContentLength");
                OnContentLengthChanged();
            }
        }
        private global::System.Int32 _ContentLength;
        partial void OnContentLengthChanging(global::System.Int32 value);
        partial void OnContentLengthChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ITintheDTestModel1", Name="ProspectiveStudentTranscript")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ProspectiveStudentTranscript : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ProspectiveStudentTranscript object.
        /// </summary>
        /// <param name="fileId">Initial value of the FileId property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="fileName">Initial value of the FileName property.</param>
        /// <param name="fileContent">Initial value of the FileContent property.</param>
        /// <param name="contentLength">Initial value of the ContentLength property.</param>
        /// <param name="contentType">Initial value of the ContentType property.</param>
        public static ProspectiveStudentTranscript CreateProspectiveStudentTranscript(global::System.Int32 fileId, global::System.Int32 userId, global::System.String fileName, global::System.Byte[] fileContent, global::System.Int32 contentLength, global::System.String contentType)
        {
            ProspectiveStudentTranscript prospectiveStudentTranscript = new ProspectiveStudentTranscript();
            prospectiveStudentTranscript.FileId = fileId;
            prospectiveStudentTranscript.UserId = userId;
            prospectiveStudentTranscript.FileName = fileName;
            prospectiveStudentTranscript.FileContent = fileContent;
            prospectiveStudentTranscript.ContentLength = contentLength;
            prospectiveStudentTranscript.ContentType = contentType;
            return prospectiveStudentTranscript;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FileId
        {
            get
            {
                return _FileId;
            }
            set
            {
                if (_FileId != value)
                {
                    OnFileIdChanging(value);
                    ReportPropertyChanging("FileId");
                    _FileId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("FileId");
                    OnFileIdChanged();
                }
            }
        }
        private global::System.Int32 _FileId;
        partial void OnFileIdChanging(global::System.Int32 value);
        partial void OnFileIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FileName
        {
            get
            {
                return _FileName;
            }
            set
            {
                OnFileNameChanging(value);
                ReportPropertyChanging("FileName");
                _FileName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FileName");
                OnFileNameChanged();
            }
        }
        private global::System.String _FileName;
        partial void OnFileNameChanging(global::System.String value);
        partial void OnFileNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] FileContent
        {
            get
            {
                return StructuralObject.GetValidValue(_FileContent);
            }
            set
            {
                OnFileContentChanging(value);
                ReportPropertyChanging("FileContent");
                _FileContent = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FileContent");
                OnFileContentChanged();
            }
        }
        private global::System.Byte[] _FileContent;
        partial void OnFileContentChanging(global::System.Byte[] value);
        partial void OnFileContentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ContentLength
        {
            get
            {
                return _ContentLength;
            }
            set
            {
                OnContentLengthChanging(value);
                ReportPropertyChanging("ContentLength");
                _ContentLength = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ContentLength");
                OnContentLengthChanged();
            }
        }
        private global::System.Int32 _ContentLength;
        partial void OnContentLengthChanging(global::System.Int32 value);
        partial void OnContentLengthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ContentType
        {
            get
            {
                return _ContentType;
            }
            set
            {
                OnContentTypeChanging(value);
                ReportPropertyChanging("ContentType");
                _ContentType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ContentType");
                OnContentTypeChanged();
            }
        }
        private global::System.String _ContentType;
        partial void OnContentTypeChanging(global::System.String value);
        partial void OnContentTypeChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ITintheDTestModel1", Name="SponsorStatu")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SponsorStatu : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SponsorStatu object.
        /// </summary>
        /// <param name="sponsorStatusId">Initial value of the SponsorStatusId property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        public static SponsorStatu CreateSponsorStatu(global::System.Int32 sponsorStatusId, global::System.String description)
        {
            SponsorStatu sponsorStatu = new SponsorStatu();
            sponsorStatu.SponsorStatusId = sponsorStatusId;
            sponsorStatu.Description = description;
            return sponsorStatu;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SponsorStatusId
        {
            get
            {
                return _SponsorStatusId;
            }
            set
            {
                if (_SponsorStatusId != value)
                {
                    OnSponsorStatusIdChanging(value);
                    ReportPropertyChanging("SponsorStatusId");
                    _SponsorStatusId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SponsorStatusId");
                    OnSponsorStatusIdChanged();
                }
            }
        }
        private global::System.Int32 _SponsorStatusId;
        partial void OnSponsorStatusIdChanging(global::System.Int32 value);
        partial void OnSponsorStatusIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ITintheDTestModel1", "FK_ProspectiveCorporateSponsor_SponsorStatus", "ProspectiveCorporateSponsor")]
        public EntityCollection<ProspectiveCorporateSponsor> ProspectiveCorporateSponsor
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ProspectiveCorporateSponsor>("ITintheDTestModel1.FK_ProspectiveCorporateSponsor_SponsorStatus", "ProspectiveCorporateSponsor");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ProspectiveCorporateSponsor>("ITintheDTestModel1.FK_ProspectiveCorporateSponsor_SponsorStatus", "ProspectiveCorporateSponsor", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ITintheDTestModel1", Name="StudentStatu")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class StudentStatu : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new StudentStatu object.
        /// </summary>
        /// <param name="studentStatusId">Initial value of the StudentStatusId property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        public static StudentStatu CreateStudentStatu(global::System.Int32 studentStatusId, global::System.String description)
        {
            StudentStatu studentStatu = new StudentStatu();
            studentStatu.StudentStatusId = studentStatusId;
            studentStatu.Description = description;
            return studentStatu;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StudentStatusId
        {
            get
            {
                return _StudentStatusId;
            }
            set
            {
                if (_StudentStatusId != value)
                {
                    OnStudentStatusIdChanging(value);
                    ReportPropertyChanging("StudentStatusId");
                    _StudentStatusId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("StudentStatusId");
                    OnStudentStatusIdChanged();
                }
            }
        }
        private global::System.Int32 _StudentStatusId;
        partial void OnStudentStatusIdChanging(global::System.Int32 value);
        partial void OnStudentStatusIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ITintheDTestModel1", "FK_ProspectiveStudent_StudentStatus1", "ProspectiveStudent")]
        public EntityCollection<ProspectiveStudent> ProspectiveStudent
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ProspectiveStudent>("ITintheDTestModel1.FK_ProspectiveStudent_StudentStatus1", "ProspectiveStudent");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ProspectiveStudent>("ITintheDTestModel1.FK_ProspectiveStudent_StudentStatus1", "ProspectiveStudent", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ITintheDTestModel1", Name="webpages_Roles")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class webpages_Roles : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new webpages_Roles object.
        /// </summary>
        /// <param name="roleId">Initial value of the RoleId property.</param>
        /// <param name="roleName">Initial value of the RoleName property.</param>
        public static webpages_Roles Createwebpages_Roles(global::System.Int32 roleId, global::System.String roleName)
        {
            webpages_Roles webpages_Roles = new webpages_Roles();
            webpages_Roles.RoleId = roleId;
            webpages_Roles.RoleName = roleName;
            return webpages_Roles;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RoleId
        {
            get
            {
                return _RoleId;
            }
            set
            {
                if (_RoleId != value)
                {
                    OnRoleIdChanging(value);
                    ReportPropertyChanging("RoleId");
                    _RoleId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RoleId");
                    OnRoleIdChanged();
                }
            }
        }
        private global::System.Int32 _RoleId;
        partial void OnRoleIdChanging(global::System.Int32 value);
        partial void OnRoleIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RoleName
        {
            get
            {
                return _RoleName;
            }
            set
            {
                OnRoleNameChanging(value);
                ReportPropertyChanging("RoleName");
                _RoleName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RoleName");
                OnRoleNameChanged();
            }
        }
        private global::System.String _RoleName;
        partial void OnRoleNameChanging(global::System.String value);
        partial void OnRoleNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ITintheDTestModel1", "fk_RoleId", "webpages_UsersInRoles")]
        public EntityCollection<webpages_UsersInRoles> webpages_UsersInRoles
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<webpages_UsersInRoles>("ITintheDTestModel1.fk_RoleId", "webpages_UsersInRoles");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<webpages_UsersInRoles>("ITintheDTestModel1.fk_RoleId", "webpages_UsersInRoles", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ITintheDTestModel1", Name="webpages_UsersInRoles")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class webpages_UsersInRoles : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new webpages_UsersInRoles object.
        /// </summary>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="roleId">Initial value of the RoleId property.</param>
        public static webpages_UsersInRoles Createwebpages_UsersInRoles(global::System.Int32 userId, global::System.Int32 roleId)
        {
            webpages_UsersInRoles webpages_UsersInRoles = new webpages_UsersInRoles();
            webpages_UsersInRoles.UserId = userId;
            webpages_UsersInRoles.RoleId = roleId;
            return webpages_UsersInRoles;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                if (_UserId != value)
                {
                    OnUserIdChanging(value);
                    ReportPropertyChanging("UserId");
                    _UserId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserId");
                    OnUserIdChanged();
                }
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RoleId
        {
            get
            {
                return _RoleId;
            }
            set
            {
                if (_RoleId != value)
                {
                    OnRoleIdChanging(value);
                    ReportPropertyChanging("RoleId");
                    _RoleId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RoleId");
                    OnRoleIdChanged();
                }
            }
        }
        private global::System.Int32 _RoleId;
        partial void OnRoleIdChanging(global::System.Int32 value);
        partial void OnRoleIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ITintheDTestModel1", "fk_RoleId", "webpages_Roles")]
        public webpages_Roles webpages_Roles
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<webpages_Roles>("ITintheDTestModel1.fk_RoleId", "webpages_Roles").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<webpages_Roles>("ITintheDTestModel1.fk_RoleId", "webpages_Roles").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<webpages_Roles> webpages_RolesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<webpages_Roles>("ITintheDTestModel1.fk_RoleId", "webpages_Roles");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<webpages_Roles>("ITintheDTestModel1.fk_RoleId", "webpages_Roles", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
